spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/agitado
    username: agitado
    password: agitado
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true